### ISSUE TITLE
Wishlist: browser extension to report I live at a given Y,X

### ISSUE THREAD

**Issue by jidanni** [AykutCevik/Geolocate-IP-Browser-Extension#12]
I live on a hill at 24.18169,120.86620. I want chromium desktop to
indeed think that is where I live, and report it when sites query my
location.

I've installed plenty of extensions, but all of them aren't very good.
E.g., Google Maps says it still can't determine my location.

I notice your extension has 5 stars. So maybe you could make an
additional extension that really works to do that. Thanks.

**Comment by AykutCevik** [comment]
The problem of IP based locations is that they aren't meant to give the exact location. A lot of people share IP addresses and providers are giving new IP addresses on every new connection.

If you have troubles with your location provider of your browser you may want to tweak it maybe with a GPS receiver.

See this [thread](https://security.stackexchange.com/questions/147166/how-can-you-fake-geolocation-in-firefox) to "fake" your position. Hope this helps. No need for an extension :)

**Comment by jidanni** [comment]
Yes one does need an extension as one does not want to type it into the console for each page. But thanks anyway.
