### ISSUE TITLE
improve visuals

### ISSUE THREAD

**Issue by mispp** [AykutCevik/Geolocate-IP-Browser-Extension#13]
- instead of globe icon, use flags
- improve contrast for text 
     - dark blue background -> yellow text; inverted colors
     - or framed box where with think border, filled white color and black text
- options in settings to select desired result

**Comment by mispp** [comment]
partially addressed in #14

**Comment by AykutCevik** [comment]
Thank you for your contribution in https://github.com/AykutCevik/Geolocate-IP-Browser-Extension/pull/14, I really appreciate it and thank you for your suggestions here. I will go through them. Also want to make it optional where the user can decide between classic globe and flag.
