### ISSUE TITLE
IPv6 Sorgusu

### ISSUE THREAD

**Issue by Mytonn** [AykutCevik/Geolocate-IP-Browser-Extension#19]
Merhaba;

IPv6 sorgusunu iptal edemiyor muyuz? IPv6 kullanmama rağmen arka planda 6 sn.de bir sorgu yapıyor.

**Comment by AykutCevik** [comment]
Hello,
Yes, this is intended to check if you have a new connection or not. Otherwise it wouldn't be able to see that you have a new IP address or not. Since these are just failing DNS requests it has no impact on your connection.
